# Generated by Django 3.2.15 on 2022-11-10 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core_main_app", "0004_template_ordering"),
        ("core_oaipmh_provider_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oaidata",
            name="data",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core_main_app.data",
            ),
        ),
        migrations.AlterField(
            model_name="oaidata",
            name="template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core_main_app.template",
            ),
        ),
    ]
